"""create tables

Revision ID: 38b4cdb77716
Revises: 
Create Date: 2023-09-13 21:51:31.708269

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '38b4cdb77716'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'users',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('email', sa.String(length=254), nullable=True),
        sa.Column('password', sa.String(length=32), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('email'),
    )
    op.create_table(
        'meetings',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('location', sa.String(length=100), nullable=True),
        sa.Column('time', sa.DateTime(), nullable=True),
        sa.Column('creator_user_id', sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ['creator_user_id'],
            ['users.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'comments',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('comment', sa.String(length=255), nullable=True),
        sa.Column('user_id', sa.UUID(), nullable=False),
        sa.Column('meeting_id', sa.Integer(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ['meeting_id'],
            ['meetings.id'],
        ),
        sa.ForeignKeyConstraint(
            ['user_id'],
            ['users.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'expenses',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('amount', sa.BigInteger(), nullable=False),
        sa.Column('owner_id', sa.UUID(), nullable=False),
        sa.Column('meeting_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ['meeting_id'],
            ['meetings.id'],
        ),
        sa.ForeignKeyConstraint(
            ['owner_id'],
            ['users.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('expenses')
    op.drop_table('comments')
    op.drop_table('meetings')
    op.drop_table('users')
    # ### end Alembic commands ###
